services:
  postgres:
    image: postgres:16
    container_name: filesapi-postgres
    environment:
      POSTGRES_DB: filesapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kamil
    ports:
      - "5433:5432"
    volumes:
      - filesapi-data:/var/lib/postgresql/data
  #filesApi:
    #image: użyj z Dockerfile

volumes:
  filesapi-data:

networks: # aby postgres i filesApi wewnątrz podu ze soba rozmawialy

