services:
  postgres:
    image: postgres:16
    container_name: filesapi-postgres
    environment:
      POSTGRES_DB: filesapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kamil
    ports:
      - "5433:5432"
    volumes:
      - filesapi-data:/var/lib/postgresql/data
  filesapi:
    build: .                       # zbuduj obraz z Dockerfile w tym samym folderze
    container_name: filesapi-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/filesapi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kamil
    depends_on:
      - postgres                   # uruchom postgres PRZED aplikacją
    networks:
      - filesapi-network

volumes:
  filesapi-data:

networks: # aby postgres i filesApi wewnątrz podu ze soba rozmawialy

